from fastapi import APIRouter, HTTPException, status, Depends
from typing import List
from app.database.mongodb import get_database
from app.models.classroom import Classroom
from app.schemas.classroom import (
    ClassroomCreate,
    ClassroomResponse,
    JoinClassroomRequest,
    JoinClassroomResponse,
    AnnouncementCreate,
    AnnouncementResponse,
)
from app.schemas.face import ClassEmbeddingResponse
from app.api.deps import get_current_user
from app.models.user import User
from app.models.notification import Notification
from app.services.email_service import email_service
import logging
import asyncio
from datetime import datetime

logger = logging.getLogger(__name__)

router = APIRouter()



#  GET /classrooms/     List classrooms

@router.get("/", response_model=List[ClassroomResponse])
async def list_classrooms(
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    - Teachers see only their own classrooms.
    - Students see only classrooms they have joined.
    """
    user_id = str(current_user.id)

    if current_user.role == "teacher":
        classrooms = await db["classrooms"].find(
            {"teacher_id": user_id}
        ).to_list(200)
    else:
        # Student: find classrooms where their id is in student_ids
        classrooms = await db["classrooms"].find(
            {"student_ids": user_id}
        ).to_list(200)

    response = []
    for cls in classrooms:
        response.append(
            ClassroomResponse(
                **cls,
                student_count=len(cls.get("student_ids", [])),
            )
        )
    return response



#  POST /classrooms/        Create classroom (teacher only)

@router.post("/", response_model=ClassroomResponse, status_code=status.HTTP_201_CREATED)
async def create_classroom(
    classroom_in: ClassroomCreate,
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    Teacher creates a new classroom.
    An access code is automatically generated and saved.
    """
    if current_user.role != "teacher":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only teachers can create classrooms",
        )

    # Build the classroom model — access_code auto-generated by the model
    classroom = Classroom(
        name=classroom_in.name,
        course_code=classroom_in.course_code,
        description=classroom_in.description,
        schedule=classroom_in.schedule,
        teacher_id=str(current_user.id),
    )

    classroom_dict = classroom.model_dump(by_alias=True)
    await db["classrooms"].insert_one(classroom_dict)

    created = await db["classrooms"].find_one({"_id": classroom.id})
    if not created:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to create classroom",
        )

    logger.info(
        f"Classroom '{classroom.name}' created by teacher {current_user.id} "
        f"with access code {classroom.access_code}"
    )

    # Trigger notification
    notification = Notification(
        user_id=str(current_user.id),
        title="Classroom Created",
        message=f"You successfully created the classroom '{classroom.name}'.",
        type="success"
    )
    await db["notifications"].insert_one(notification.model_dump(by_alias=True, exclude_none=True))

    return ClassroomResponse(
        **created,
        student_count=0,
    )


#  POST /classrooms/join    Student joins via access code

@router.post("/join", response_model=JoinClassroomResponse)
async def join_classroom(
    join_in: JoinClassroomRequest,
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    Student provides an access code to join the matching classroom.
    The student's user ID is added to classroom.student_ids.
    """
    if current_user.role != "student":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only students can join classrooms",
        )

    user_id = str(current_user.id)
    access_code = join_in.access_code.strip().upper()

    # 1. Find the classroom by access code
    classroom = await db["classrooms"].find_one({"access_code": access_code})
    if not classroom:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Invalid access code. No classroom found.",
        )

    classroom_id = str(classroom["_id"])

    # 2. Check if student is already enrolled
    if user_id in classroom.get("student_ids", []):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="You have already joined this classroom.",
        )

    # 3. Add student to the classroom
    result = await db["classrooms"].update_one(
        {"_id": classroom_id},
        {"$addToSet": {"student_ids": user_id}},
    )

    if result.modified_count == 0:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to join classroom. Please try again.",
        )

    logger.info(
        f"Student {user_id} joined classroom '{classroom['name']}' "
        f"(id={classroom_id}) via access code {access_code}"
    )

    # Trigger notification
    notification = Notification(
        user_id=user_id,
        title="Joined Classroom",
        message=f"You successfully joined the classroom '{classroom['name']}'.",
        type="success"
    )
    await db["notifications"].insert_one(notification.model_dump(by_alias=True, exclude_none=True))

    # Trigger email
    if current_user.email:
        asyncio.create_task(
            email_service.send_class_join_confirmation(
                email=current_user.email,
                student_name=current_user.full_name or "Student",
                class_name=classroom["name"],
                date_time=datetime.utcnow()
            )
        )

    return JoinClassroomResponse(
        message=f"Successfully joined '{classroom['name']}'!",
        classroom_id=classroom_id,
        classroom_name=classroom["name"],
    )



#  GET /classrooms/{class_id}   Get single classroom

@router.get("/{class_id}", response_model=ClassroomResponse)
async def get_classroom(
    class_id: str,
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    Get a single classroom by ID.
    """
    classroom = await db["classrooms"].find_one({"_id": class_id})
    if not classroom:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Classroom {class_id} not found",
        )
    return ClassroomResponse(
        **classroom,
        student_count=len(classroom.get("student_ids", [])),
    )



#  GET /classrooms/{class_id}/embeddings

@router.get("/{class_id}/embeddings", response_model=List[ClassEmbeddingResponse])
async def get_class_embeddings(
    class_id: str,
    db=Depends(get_database),
):
    """
    Get all face embeddings for students in a specific class.
    Used by the recognition system to load authorized faces.
    """
    classroom = await db["classrooms"].find_one({"_id": class_id})
    if not classroom:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Classroom with ID {class_id} not found",
        )

    pipeline = [
        {"$match": {"classroom_id": class_id}},
        {
            "$lookup": {
                "from": "face_embeddings",
                "localField": "face_embedding_id",
                "foreignField": "_id",
                "as": "embedding_data",
            }
        },
        {"$unwind": "$embedding_data"},
        {
            "$project": {
                "student_id": "$_id",
                "name": 1,
                "roll_number": 1,
                "embedding": "$embedding_data.embedding",
            }
        },
    ]

    try:
        results = await db["students"].aggregate(pipeline).to_list(None)
        return results
    except Exception as e:
        logger.error(f"Failed to aggregate class embeddings: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Error retrieving class embeddings",
        )



#  DELETE /classrooms/{class_id}    Delete a classroom

@router.delete("/{class_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_classroom(
    class_id: str,
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    Delete a classroom by ID.
    Only the teacher who created the classroom can delete it.
    """
    if current_user.role != "teacher":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only teachers can delete classrooms",
        )

    classroom = await db["classrooms"].find_one({"_id": class_id})
    if not classroom:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Classroom {class_id} not found",
        )

    if str(classroom.get("teacher_id")) != str(current_user.id):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You can only delete your own classrooms",
        )

    result = await db["classrooms"].delete_one({"_id": class_id})
    
    if result.deleted_count == 0:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to delete classroom",
        )

    logger.info(f"Classroom {class_id} deleted by teacher {current_user.id}")

    # Notify teacher
    teacher_notification = Notification(
        user_id=str(current_user.id),
        title="Classroom Deleted",
        message=f"You successfully deleted the classroom '{classroom.get('name')}'.",
        type="info"
    )
    await db["notifications"].insert_one(teacher_notification.model_dump(by_alias=True, exclude_none=True))

    # Notify students
    student_ids = classroom.get("student_ids", [])
    if student_ids:
        student_notifications = [
            Notification(
                user_id=sid,
                title="Classroom Deleted",
                message=f"The classroom '{classroom.get('name')}' has been deleted by the teacher.",
                type="warning"
            ).model_dump(by_alias=True, exclude_none=True)
            for sid in student_ids
        ]
        if student_notifications:
            await db["notifications"].insert_many(student_notifications)

    return {"message": "Classroom deleted successfully"}



#  POST /classrooms/{class_id}/leave    Student leaves a classroom

@router.post("/{class_id}/leave", status_code=status.HTTP_200_OK)
async def leave_classroom(
    class_id: str,
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    Student leaves a classroom they have joined.
    """
    if current_user.role != "student":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only students can leave classrooms",
        )

    user_id = str(current_user.id)

    # Find the classroom
    classroom = await db["classrooms"].find_one({"_id": class_id})
    if not classroom:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Classroom {class_id} not found",
        )

    # Check if student is actually enrolled
    if user_id not in classroom.get("student_ids", []):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="You are not enrolled in this classroom",
        )

    # Remove student from the classroom's student_ids array
    result = await db["classrooms"].update_one(
        {"_id": class_id},
        {"$pull": {"student_ids": user_id}}
    )

    if result.modified_count == 0:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to leave classroom. Please try again.",
        )

    logger.info(f"Student {user_id} left classroom '{classroom.get('name')}' (id={class_id})")

    # Notify student
    notification = Notification(
        user_id=user_id,
        title="Left Classroom",
        message=f"You successfully left the classroom '{classroom.get('name')}'.",
        type="info"
    )
    await db["notifications"].insert_one(notification.model_dump(by_alias=True, exclude_none=True))

    return {"message": f"Successfully left '{classroom.get('name')}'"}


#  POST /classrooms/{class_id}/announcements    Create an announcement

@router.post("/{class_id}/announcements", response_model=AnnouncementResponse, status_code=status.HTTP_201_CREATED)
async def create_announcement(
    class_id: str,
    announcement_in: AnnouncementCreate,
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    Teacher creates a new announcement for their classroom.
    """
    if current_user.role != "teacher":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only teachers can create announcements",
        )

    # 1. Verify classroom exists and belongs to teacher
    classroom = await db["classrooms"].find_one({"_id": class_id})
    if not classroom:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Classroom {class_id} not found",
        )

    if str(classroom.get("teacher_id")) != str(current_user.id):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You can only create announcements for your own classrooms",
        )

    # 2. Create the announcement document
    from datetime import datetime
    announcement_data = {
        "classroom_id": class_id,
        "teacher_id": str(current_user.id),
        "teacher_name": current_user.full_name or "Teacher",
        "content": announcement_in.content,
        "created_at": datetime.utcnow()
    }

    result = await db["announcements"].insert_one(announcement_data)
    
    created_announcement = await db["announcements"].find_one({"_id": result.inserted_id})
    if not created_announcement:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to create announcement",
        )

    logger.info(f"Teacher {current_user.id} created announcement in classroom {class_id}")
    
    # Cast _id locally for the response model
    created_announcement["_id"] = str(created_announcement["_id"])
    return AnnouncementResponse(**created_announcement)


#  GET /classrooms/{class_id}/announcements     List announcements

@router.get("/{class_id}/announcements", response_model=List[AnnouncementResponse])
async def list_announcements(
    class_id: str,
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    Get all announcements for a classroom. 
    Teachers must own it; students must be enrolled.
    """
    # 1. Verify classroom access
    classroom = await db["classrooms"].find_one({"_id": class_id})
    if not classroom:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Classroom {class_id} not found",
        )

    user_id = str(current_user.id)
    if current_user.role == "teacher":
        if str(classroom.get("teacher_id")) != user_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="You do not have access to this classroom",
            )
    else:
        # Check student enrollment
        if user_id not in classroom.get("student_ids", []):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="You must join the classroom to view announcements",
            )

    # 2. Fetch announcements, newest first
    cursor = db["announcements"].find({"classroom_id": class_id}).sort("created_at", -1)
    announcements = await cursor.to_list(length=100)
    
    # 3. Format response
    response = []
    for ann in announcements:
        ann["_id"] = str(ann["_id"])
        response.append(AnnouncementResponse(**ann))
        
    return response


#  DELETE /classrooms/{class_id}/announcements/{announcement_id}     Delete an announcement

@router.delete("/{class_id}/announcements/{announcement_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_announcement(
    class_id: str,
    announcement_id: str,
    db=Depends(get_database),
    current_user: User = Depends(get_current_user),
):
    """
    Delete an announcement.
    Only the teacher who created the classroom can delete announcements within it.
    """
    if current_user.role != "teacher":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only teachers can delete announcements",
        )

    # 1. Verify classroom access
    classroom = await db["classrooms"].find_one({"_id": class_id})
    if not classroom:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Classroom {class_id} not found",
        )

    if str(classroom.get("teacher_id")) != str(current_user.id):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You can only delete announcements for your own classrooms",
        )

    from bson import ObjectId
    try:
        obj_id = ObjectId(announcement_id)
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid announcement ID format"
        )

    # 2. Check and delete
    result = await db["announcements"].delete_one({"_id": obj_id, "classroom_id": class_id})
    
    if result.deleted_count == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Announcement not found in this classroom",
        )

    logger.info(f"Teacher {current_user.id} deleted announcement {announcement_id} in classroom {class_id}")
    return {"message": "Announcement deleted successfully"}
